version: '3'

services:
  php:
    build:
      context: ./
      dockerfile: app.dockerfile
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=db"

  nginx:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    ports:
      - 80:80
    volumes:
      - ./:/var/www

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: schedule_belyakov
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: belyakov
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: